#!/usr/bin/python3
# -*- coding: utf-8 -*-

import os
import sys
import subprocess

if __name__ == "__main__":
    pgrep = subprocess.getoutput("pgrep slimbookface")
    numProcRunning = pgrep.split('\n')
    if len(numProcRunning) > 1:
        print('Slimbook Face is in execution')
    else:
        os.system('python3 /usr/share/slimbookface/src/slimbookface.py')
exit(0)